sudo: required
language: go
services:
  - docker

env:
  global:
    - TF_ACC=1
    - TF_LOG=DEBUG
    - SENSU_API_URL=http://127.0.0.1:8080
    - SENSU_USERNAME=admin
    - SENSU_PASSWORD=P@ssw0rd!
    - SENSU_ENVIRONMENT=default
    - SENSU_ORGANIZATION=default
  matrix:
    - SENSU_VERSION="5.9.0"

go:
  - '1.12'

go_import_path: github.com/jtopjian/terraform-provider-sensu

matrix:
  fast_finish: true
  allow_failures:
    - env: SENSU_VERSION="5.9.0"

before_install:
  - docker pull sensu/sensu:${SENSU_VERSION}
  - docker run -v /var/lib/sensu:/var/lib/sensu -d --name sensu-backend -p 2380:2380 -p 3000:3000 -p 8080:8080 -p 8081:8081 sensu/sensu:${SENSU_VERSION} sensu-backend start
  - docker run -v /var/lib/sensu:/var/lib/sensu -d --name sensu-agent sensu/sensu:${SENSU_VERSION} sensu-agent start --backend-url ws://localhost:8081 --subscriptions webserver,system --cache-dir /var/lib/sensu

script:
  - make fmtcheck
  - make vet
  - make testacc
